# Generated by Django 4.2.9 on 2024-01-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='user',
        ),
    ]
