# Generated by Django 4.2.9 on 2024-01-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_workspace_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Workspace',
        ),
    ]
